fields:
  video_id: video_id
  question_id: key
  question: question
  answer: answer
  reasoning: ""
  choices_prefix: answer_choice_
  frames: frames
  frame_labels: frame_labels
  bboxes: bbox_pix
  enlarge_out: enlarge_latent
  bbox_out: "boundingbox_latent"

download:
  overrides:
    url: url

keyframes:
  params:
    min_select: 4
    k_candidates: 100
    candidate_max_wh: 512
    candidate_jpeg_q: 4
    close_sec: 0.5
    model: gpt-4o
    temperature: 0.0

labels:
  params:
    model: gpt-4o
    temperature: 0.0

bbox:
  params:
    model_id: IDEA-Research/grounding-dino-base
    box_threshold: 0.30
    text_threshold: 0.25

latents:
  params:
    rel_root_enlarge: /latent/enlarge
    rel_root_bbox: /latent/bbox
    filename_template: keyframe_{i}.png
    draw_width: 3
    padding_pix: 0
    resize_short: 0